**Data Cleaning**

In [5]:
import pandas as pd

In [7]:
df = pd.read_excel(r"C:\Users\gerar\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [8]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [9]:
df = df.drop(columns = 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [10]:
df['Last_Name'] = df['Last_Name'].str.strip('./_')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [12]:
df['Phone_Number'] = df['Phone_Number'].str.replace('[^0-9]', '', regex=True) # Quitar signos en medio
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [17]:
df['Phone_Number'].apply(lambda x: str(x)) # Convertir la col en str
# Aplicar el formato adecuado a los números de teléfono, manejando los NaN
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10] if isinstance(x, str) and len(x) == 10 else x)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [19]:
df['Phone_Number'] = df['Phone_Number'].fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [21]:
df['Address'].str.split(',', n = 2, expand = True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [23]:
df[['Street_Adress', 'State', 'Zip_Code']] = df['Address'].str.split(',', n = 2, expand = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [25]:
df = df.drop(columns = 'Address')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [27]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [29]:
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y', regex=True)
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N', regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [31]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y', regex=True)
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N', regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [33]:
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [35]:
df = df.replace('N/a', '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

**Ahora no queremos que el call center tenga los contactos de las personas que no quieren ser contactadas**

In [54]:
df.drop(df[df['Do_Not_Contact'] == 'Y'].index, inplace=True)

In [56]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [58]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.strip()

In [64]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,,N,N,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,N,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,N,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,N,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [74]:
df = df.reset_index()
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,2,1003,Walter,White,,N,N,298 Drugs Driveway,,
2,4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
3,6,1007,Jeff,Winger,,N,N,1209 South Street,,
4,7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
5,8,1009,Gandalf,,,Y,N,123 Middle Earth,,
6,9,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
7,10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
8,11,1012,Harry,Potter,,Y,N,2394 Hogwarts Avenue,,
9,12,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
10,13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
11,14,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
12,15,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
13,16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
14,17,1018,Clark,Kent,,Y,N,3498 Super Lane,,
15,19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [80]:
df = df.drop(columns = 'index')
df

KeyError: "['index'] not found in axis"

In [82]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire,
1,1003,Walter,White,,N,N,298 Drugs Driveway,,
2,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
3,1007,Jeff,Winger,,N,N,1209 South Street,,
4,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
5,1009,Gandalf,,,Y,N,123 Middle Earth,,
6,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York,
7,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
8,1012,Harry,Potter,,Y,N,2394 Hogwarts Avenue,,
9,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,,
10,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
11,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,,
12,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,,
13,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
14,1018,Clark,Kent,,Y,N,3498 Super Lane,,
15,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [84]:
#Another way to drop null values
#df = df.dropna(subset="Phone_Number"), inplace=True)

In [86]:
df = df.drop(columns = 'Zip_Code')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,Shire
1,1003,Walter,White,,N,N,298 Drugs Driveway,
2,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,
3,1007,Jeff,Winger,,N,N,1209 South Street,
4,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,
5,1009,Gandalf,,,Y,N,123 Middle Earth,
6,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York
7,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire
8,1012,Harry,Potter,,Y,N,2394 Hogwarts Avenue,
9,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,
10,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,
11,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,
12,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,
13,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania
14,1018,Clark,Kent,,Y,N,3498 Super Lane,
15,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine

In [88]:
df['State'] = df['State'].str.replace('Shire', '')

In [90]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street_Adress,State
0,1001,Frodo,Baggins,123-545-5421,Y,N,123 Shire Lane,
1,1003,Walter,White,,N,N,298 Drugs Driveway,
2,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,
3,1007,Jeff,Winger,,N,N,1209 South Street,
4,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,
5,1009,Gandalf,,,Y,N,123 Middle Earth,
6,1010,Peter,Parker,123-545-5421,Y,N,25th Main Street,New York
7,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,
8,1012,Harry,Potter,,Y,N,2394 Hogwarts Avenue,
9,1013,Don,Draper,123-543-2345,Y,N,2039 Main Street,
10,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,
11,1015,Toby,Flenderson,304-762-2467,N,N,214 HR Avenue,
12,1016,Ron,Weasley,123-545-5421,N,N,2395 Hogwarts Avenue,
13,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania
14,1018,Clark,Kent,,Y,N,3498 Super Lane,
15,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine

**CLEAN!**